spring.application.name=appointment-service
server.port=8086
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://salon:salon@salon.obrfffe.mongodb.net/?retryWrites=true&w=majority}
spring.data.mongodb.database=appointment_service_db
springdoc.api-docs.path=/appointments/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true